config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_bash_profile:
    src: bash_profile
    dst: ~/.bash_profile
    link: link
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
    link: link
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
    link: link
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
    link: link
  f_gitignore:
    src: gitignore
    dst: ~/.gitignore
    link: link
  f_init.vim:
    src: config/nvim/init.vim
    dst: ~/.config/nvim/init.vim
    link: link
  f_coc.vim:
    src: config/nvim/coc.vim
    dst: ~/.config/nvim/coc.vim
  f_coc-settings.json:
    src: config/nvim/coc-settings.json
    dst: ~/.config/nvim/coc-settings.json
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
profiles:
  hornburg:
    dotfiles:
    - f_bash_profile
    - f_bashrc
    - f_tmux.conf
    - f_gitconfig
    - f_gitignore
    - f_init.vim
    - f_coc.vim
    - f_coc-settings.json
    - f_zshrc
  nsidc-kbeam-484:
    dotfiles:
    - f_bash_profile
    - f_bashrc
    - f_tmux.conf
    - f_gitconfig
    - f_gitignore
    - f_init.vim
    - f_coc.vim
    - f_coc-settings.json
    - f_zshrc
